# Generated by Django 6.0.7 on 2026-07-18 18:16

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(validators=[apps.books.models.validate_year]),
        ),
    ]
